title: Anders Bo Justesen
description: My research interests are exoplanetary systems and binary stars. I'm particularly interested in the formation and dynamical evolution of these systems. 
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman